databases:
  - name: task0
    plan: free
    databaseName: task0
    user: config

services:
  - type: web
    plan: free
    name: weather_server
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: db_url
        fromDatabase:
          name: task0
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: URL
        value: False
      - key: 
        value: False
      